# Generated by Django 5.1 on 2024-08-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorygame', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
